language: python
python:
  - 3.8
install:
  - pip install -r requirements_travis.txt
branches:
  only:
    - master
script:
  - "flake8 ."
  - "isort . --check"
  - "coverage run --source='.' -m pytest"
after_success:
  - coveralls
